import type { PortfolioOrg, GrantApplication } from "./types";

const now = Date.now();
const day = 86400000;

export const SEED_PORTFOLIO: PortfolioOrg[] = [
  {
    ein: 131760110,
    strein: "13-1760110",
    name: "Teach For America",
    city: "New York",
    state: "NY",
    ntee_code: "B400",
    stage: "assessed",
    addedAt: now - 14 * day,
    analyzedAt: now - 13 * day,
    analysisData: {
      org: {
        ein: 131760110,
        name: "Teach For America",
        city: "New York",
        state: "NY",
        ntee_code: "B400",
        ruling_date: "199312",
      },
      readiness: {
        overall: 86,
        tier: "Grant-Ready",
        financial: {
          score: 90,
          checks: [
            ["Revenue over $250K", true, 25],
            ["Positive net assets", true, 20],
            ["Revenue growth trend", true, 15],
            ["Diversified revenue streams", true, 15],
            ["Reasonable overhead ratio", true, 10],
            ["Operating reserves available", true, 15],
          ],
        },
        compliance: {
          score: 85,
          checks: [
            ["Filed 990 in last 2 years", true, 30],
            ["No late filings", true, 20],
            ["Ruling date > 3 years ago", true, 20],
            ["NTEE code assigned", true, 10],
            ["Consistent EIN history", true, 10],
            ["Board members listed", false, 10],
          ],
        },
        digital: {
          score: 82,
          checks: [
            ["Website is reachable", true, 15],
            ["Has SSL certificate", true, 10],
            ["Mission statement visible", true, 15],
            ["Donation page present", true, 15],
            ["Annual report available", true, 10],
            ["Board page exists", true, 10],
            ["Contact info visible", true, 10],
            ["Social media links", true, 5],
            ["Copyright year current", false, 5],
            ["Word count adequate (>500)", true, 5],
          ],
        },
        gaps: ["Board members not listed in filing"],
        weights: { financial: 0.35, compliance: 0.25, digital: 0.4 },
      },
      grantMatches: [
        {
          name: "Bill & Melinda Gates Foundation",
          focus: "Education",
          url: "https://www.gatesfoundation.org",
          type: "Private Foundation",
          avg_grant: 500000,
          grant_range: [100000, 2000000] as [number, number],
          deadline: "Rolling",
          match_pct: 92,
          fits: ["Education focus", "National reach", "Track record"],
          blockers: [],
          eligible: true,
          requires: ["501c3", "Audited financials"],
        },
        {
          name: "Walton Family Foundation",
          focus: "K-12 Education Reform",
          url: "https://www.waltonfamilyfoundation.org",
          type: "Private Foundation",
          avg_grant: 350000,
          grant_range: [50000, 1000000] as [number, number],
          deadline: "March 15",
          match_pct: 85,
          fits: ["K-12 education", "Policy alignment"],
          blockers: [],
          eligible: true,
          requires: ["501c3"],
        },
        {
          name: "Carnegie Corporation of New York",
          focus: "Education & Equity",
          url: "https://www.carnegie.org",
          type: "Private Foundation",
          avg_grant: 250000,
          grant_range: [50000, 750000] as [number, number],
          deadline: "September 1",
          match_pct: 78,
          fits: ["Education equity", "Teacher pipeline"],
          blockers: ["Competitive cycle"],
          eligible: true,
          requires: ["501c3", "Evaluation plan"],
        },
      ],
      actionItems: [
        { action: "Add board member listing to 990 filing", unlocks: 1, category: "compliance", priority: "medium" },
        { action: "Update website copyright year", unlocks: 0, category: "digital", priority: "low" },
        { action: "Publish annual impact report on website", unlocks: 2, category: "digital", priority: "high" },
      ],
      siteScan: {
        url: "https://www.teachforamerica.org",
        reachable: true,
        error: null,
        title: "Teach For America",
        meta_description: "Teach For America works to enlist, develop, and mobilize as many as possible of our nation's most promising future leaders to grow and strengthen the movement for educational equity and excellence.",
        signals: { ssl: true, mission: true, donate: true, annual_report: true, board: true, contact: true, social: true },
        footer_year: 2025,
        word_count: 2400,
        pages_checked: ["/", "/about", "/donate"],
        low_content_warning: false,
      },
      websiteUrl: "https://www.teachforamerica.org",
    },
  },
  {
    ein: 363722735,
    strein: "36-3722735",
    name: "Chicago Youth Programs",
    city: "Chicago",
    state: "IL",
    ntee_code: "O20",
    stage: "fixing",
    addedAt: now - 10 * day,
    analyzedAt: now - 9 * day,
    analysisData: {
      org: {
        ein: 363722735,
        name: "Chicago Youth Programs",
        city: "Chicago",
        state: "IL",
        ntee_code: "O20",
        ruling_date: "200805",
      },
      readiness: {
        overall: 58,
        tier: "Needs Work",
        financial: {
          score: 55,
          checks: [
            ["Revenue over $250K", true, 25],
            ["Positive net assets", true, 20],
            ["Revenue growth trend", false, 15],
            ["Diversified revenue streams", false, 15],
            ["Reasonable overhead ratio", true, 10],
            ["Operating reserves available", false, 15],
          ],
        },
        compliance: {
          score: 70,
          checks: [
            ["Filed 990 in last 2 years", true, 30],
            ["No late filings", false, 20],
            ["Ruling date > 3 years ago", true, 20],
            ["NTEE code assigned", true, 10],
            ["Consistent EIN history", true, 10],
            ["Board members listed", true, 10],
          ],
        },
        digital: {
          score: 45,
          checks: [
            ["Website is reachable", true, 15],
            ["Has SSL certificate", false, 10],
            ["Mission statement visible", true, 15],
            ["Donation page present", false, 15],
            ["Annual report available", false, 10],
            ["Board page exists", false, 10],
            ["Contact info visible", true, 10],
            ["Social media links", false, 5],
            ["Copyright year current", false, 5],
            ["Word count adequate (>500)", true, 5],
          ],
        },
        gaps: ["Revenue declining", "No SSL certificate", "Missing donation page", "Late filing history"],
        weights: { financial: 0.35, compliance: 0.25, digital: 0.4 },
      },
      grantMatches: [
        {
          name: "MacArthur Foundation",
          focus: "Community Development",
          url: "https://www.macfound.org",
          type: "Private Foundation",
          avg_grant: 200000,
          grant_range: [25000, 500000] as [number, number],
          deadline: "Rolling",
          match_pct: 65,
          fits: ["Chicago-based", "Youth focus"],
          blockers: ["Late filing", "No SSL"],
          eligible: false,
          requires: ["501c3", "Clean filing history"],
        },
        {
          name: "Chicago Community Trust",
          focus: "Youth Development",
          url: "https://www.cct.org",
          type: "Community Foundation",
          avg_grant: 75000,
          grant_range: [10000, 200000] as [number, number],
          deadline: "June 1",
          match_pct: 72,
          fits: ["Local org", "Youth services"],
          blockers: ["Missing online donation page"],
          eligible: true,
          requires: ["501c3", "Chicago-based"],
        },
      ],
      actionItems: [
        { action: "Install SSL certificate on website", unlocks: 2, category: "digital", priority: "high" },
        { action: "Add online donation page", unlocks: 3, category: "digital", priority: "high" },
        { action: "File 990 on time this cycle", unlocks: 1, category: "compliance", priority: "high" },
        { action: "Diversify revenue beyond program fees", unlocks: 1, category: "financial", priority: "medium" },
        { action: "Build operating reserve fund", unlocks: 0, category: "financial", priority: "medium" },
        { action: "Add board page to website", unlocks: 1, category: "digital", priority: "medium" },
        { action: "Link social media accounts", unlocks: 0, category: "digital", priority: "low" },
      ],
      siteScan: {
        url: "https://chicagoyouthprograms.org",
        reachable: true,
        error: null,
        title: "Chicago Youth Programs",
        meta_description: null,
        signals: { ssl: false, mission: true, donate: false, annual_report: false, board: false, contact: true, social: false },
        footer_year: 2022,
        word_count: 650,
        pages_checked: ["/", "/about"],
        low_content_warning: false,
      },
      websiteUrl: "https://chicagoyouthprograms.org",
    },
  },
  {
    ein: 582060131,
    strein: "58-2060131",
    name: "Habitat for Humanity",
    city: "Atlanta",
    state: "GA",
    ntee_code: "L210",
    stage: "ready",
    addedAt: now - 21 * day,
    analyzedAt: now - 20 * day,
    analysisData: {
      org: {
        ein: 582060131,
        name: "Habitat for Humanity",
        city: "Atlanta",
        state: "GA",
        ntee_code: "L210",
        ruling_date: "197610",
      },
      readiness: {
        overall: 94,
        tier: "Grant-Ready",
        financial: {
          score: 95,
          checks: [
            ["Revenue over $250K", true, 25],
            ["Positive net assets", true, 20],
            ["Revenue growth trend", true, 15],
            ["Diversified revenue streams", true, 15],
            ["Reasonable overhead ratio", true, 10],
            ["Operating reserves available", true, 15],
          ],
        },
        compliance: {
          score: 95,
          checks: [
            ["Filed 990 in last 2 years", true, 30],
            ["No late filings", true, 20],
            ["Ruling date > 3 years ago", true, 20],
            ["NTEE code assigned", true, 10],
            ["Consistent EIN history", true, 10],
            ["Board members listed", true, 10],
          ],
        },
        digital: {
          score: 92,
          checks: [
            ["Website is reachable", true, 15],
            ["Has SSL certificate", true, 10],
            ["Mission statement visible", true, 15],
            ["Donation page present", true, 15],
            ["Annual report available", true, 10],
            ["Board page exists", true, 10],
            ["Contact info visible", true, 10],
            ["Social media links", true, 5],
            ["Copyright year current", true, 5],
            ["Word count adequate (>500)", true, 5],
          ],
        },
        gaps: [],
        weights: { financial: 0.35, compliance: 0.25, digital: 0.4 },
      },
      grantMatches: [
        {
          name: "Ford Foundation",
          focus: "Housing & Community Development",
          url: "https://www.fordfoundation.org",
          type: "Private Foundation",
          avg_grant: 400000,
          grant_range: [50000, 1500000] as [number, number],
          deadline: "Rolling",
          match_pct: 95,
          fits: ["Housing focus", "Global reach", "Strong financials"],
          blockers: [],
          eligible: true,
          requires: ["501c3"],
        },
        {
          name: "JPMorgan Chase Foundation",
          focus: "Affordable Housing",
          url: "https://www.jpmorganchase.com/impact",
          type: "Corporate Foundation",
          avg_grant: 250000,
          grant_range: [25000, 1000000] as [number, number],
          deadline: "April 30",
          match_pct: 88,
          fits: ["Housing mission", "National scale"],
          blockers: [],
          eligible: true,
          requires: ["501c3", "Audited financials"],
        },
      ],
      actionItems: [],
      siteScan: {
        url: "https://www.habitat.org",
        reachable: true,
        error: null,
        title: "Habitat for Humanity",
        meta_description: "Habitat for Humanity is a global nonprofit housing organization working in local communities across all 50 states and in approximately 70 countries.",
        signals: { ssl: true, mission: true, donate: true, annual_report: true, board: true, contact: true, social: true },
        footer_year: 2026,
        word_count: 4200,
        pages_checked: ["/", "/about", "/donate", "/volunteer"],
        low_content_warning: false,
      },
      websiteUrl: "https://www.habitat.org",
    },
  },
  {
    ein: 953211478,
    strein: "95-3211478",
    name: "Green Spaces LA",
    city: "Los Angeles",
    state: "CA",
    ntee_code: "C340",
    stage: "intake",
    addedAt: now - 2 * day,
    analysisData: null,
  },
  {
    ein: 270618426,
    strein: "27-0618426",
    name: "Rural Health Initiative",
    city: "Helena",
    state: "MT",
    ntee_code: "E320",
    stage: "intake",
    addedAt: now - 1 * day,
    analysisData: null,
  },
];

export const SEED_APPLICATIONS: GrantApplication[] = [
  {
    id: "app_seed_1",
    status: "new",
    submittedAt: now - 3 * 3600000,
    updatedAt: now - 3 * 3600000,
    notes: "",
    orgName: "Community Builders Alliance",
    ein: "45-1234567",
    website: "https://communitybuilders.org",
    missionStatement: "We empower underserved communities through education, workforce training, and neighborhood revitalization programs.",
    annualBudget: "$500,000 – $1,000,000",
    contactName: "Maria Santos",
    contactEmail: "maria@communitybuilders.org",
    contactPhone: "(312) 555-0199",
    contactTitle: "Executive Director",
    projectTitle: "Neighborhood Youth Leadership Academy",
    projectDescription: "A 12-month after-school program providing leadership training, mentorship, and college prep workshops for 200 youth ages 14-19 in underserved neighborhoods. Expected outcomes include 90% high school graduation rate and 75% college enrollment among participants.",
    amountRequested: "$75,000",
    projectTimeline: "12 months starting March 2027",
    targetPopulation: "Low-income youth ages 14-19 in Chicago's South Side",
    programAreas: "Education, Workforce Development, Housing",
    referralSource: "Referral from another organization",
  },
  {
    id: "app_seed_2",
    status: "reviewing",
    submittedAt: now - 3 * day,
    updatedAt: now - 1 * day,
    notes: "Strong application. Mission aligns well with several funders in our network. Need to verify 990 filing status before proceeding.",
    orgName: "Appalachian Arts Collective",
    ein: "62-8834219",
    website: "https://appalachianarts.org",
    missionStatement: "Preserving and promoting traditional Appalachian arts, music, and craft traditions while creating economic opportunities for rural artists and artisans.",
    annualBudget: "$100,000 – $500,000",
    contactName: "James Whitaker",
    contactEmail: "james@appalachianarts.org",
    contactPhone: "(304) 555-0742",
    contactTitle: "Program Director",
    projectTitle: "Heritage Artisan Marketplace & Workshop Series",
    projectDescription: "Development of an online marketplace and quarterly in-person workshop series connecting 50+ Appalachian artisans with national buyers. Includes digital skills training, product photography support, and marketing assistance for participating artists.",
    amountRequested: "$120,000",
    projectTimeline: "18 months starting January 2027",
    targetPopulation: "Rural artisans and craftspeople in West Virginia, Kentucky, and Virginia",
    programAreas: "Arts & Culture, Economic Development, Rural Communities",
    referralSource: "Conference or event",
  },
  {
    id: "app_seed_3",
    status: "new",
    submittedAt: now - 8 * 3600000,
    updatedAt: now - 8 * 3600000,
    notes: "",
    orgName: "Pacific Northwest Food Bank Network",
    ein: "91-0034521",
    website: "https://pnwfoodbanks.org",
    missionStatement: "Coordinating food rescue and distribution across 40+ food banks in Washington and Oregon to eliminate hunger in the Pacific Northwest.",
    annualBudget: "$1,000,000 – $5,000,000",
    contactName: "Lisa Chen",
    contactEmail: "lchen@pnwfoodbanks.org",
    contactPhone: "(206) 555-0388",
    contactTitle: "Chief Development Officer",
    projectTitle: "Cold Chain Infrastructure Upgrade",
    projectDescription: "Upgrade refrigeration and cold storage capacity across 15 rural food bank locations to reduce food waste by 40% and expand fresh produce distribution to 25,000 additional families per year.",
    amountRequested: "$250,000",
    projectTimeline: "24 months starting June 2027",
    targetPopulation: "Food-insecure families in rural Washington and Oregon",
    programAreas: "Food Security, Infrastructure, Public Health",
    referralSource: "Web search",
  },
  {
    id: "app_seed_4",
    status: "approved",
    submittedAt: now - 12 * day,
    updatedAt: now - 5 * day,
    notes: "Approved for full consulting engagement. Strong digital presence, clean financials. Connected with Gates Foundation contact for education portfolio review.",
    orgName: "Digital Equity Now",
    ein: "84-3291054",
    website: "https://digitalequitynow.org",
    missionStatement: "Closing the digital divide by providing free internet access, devices, and digital literacy training to underserved communities nationwide.",
    annualBudget: "$500,000 – $1,000,000",
    contactName: "Andre Williams",
    contactEmail: "andre@digitalequitynow.org",
    contactPhone: "(415) 555-0921",
    contactTitle: "Founder & CEO",
    projectTitle: "Connected Communities Initiative",
    projectDescription: "Establishing 20 community technology centers in underserved urban neighborhoods, providing free broadband access, refurbished devices, and weekly digital literacy classes serving 5,000+ residents annually.",
    amountRequested: "$180,000",
    projectTimeline: "12 months starting September 2027",
    targetPopulation: "Low-income urban residents without reliable internet access",
    programAreas: "Technology, Education, Community Development",
    referralSource: "Social media",
  },
  {
    id: "app_seed_5",
    status: "info_needed",
    submittedAt: now - 7 * day,
    updatedAt: now - 2 * day,
    notes: "Requested audited financials and board roster. Waiting on response from contact.",
    orgName: "Sunrise Senior Services",
    ein: "73-5521890",
    website: "https://sunriseseniors.org",
    missionStatement: "Providing in-home care, meal delivery, and social engagement programs for isolated seniors in rural Oklahoma communities.",
    annualBudget: "Under $100,000",
    contactName: "Patricia Hernandez",
    contactEmail: "phernandez@sunriseseniors.org",
    contactPhone: "(918) 555-0614",
    contactTitle: "Board President",
    projectTitle: "Meals & Companionship Home Visit Program",
    projectDescription: "Expanding our volunteer-driven home visit program to deliver 3 meals per week and weekly companionship visits to 150 homebound seniors across 5 rural counties.",
    amountRequested: "$35,000",
    projectTimeline: "12 months starting April 2027",
    targetPopulation: "Homebound seniors 65+ in rural eastern Oklahoma",
    programAreas: "Elder Care, Nutrition, Social Services",
    referralSource: "Newsletter / email",
  },
  {
    id: "app_seed_6",
    status: "approved",
    submittedAt: now - 30 * day,
    updatedAt: now - 20 * day,
    notes: "Strong national org. Accepted into readiness program. Consultant assigned.",
    orgName: "Teach For America",
    ein: "13-1760110",
    website: "https://www.teachforamerica.org",
    missionStatement: "Enlisting, developing, and mobilizing as many as possible of our nation's most promising future leaders to grow and strengthen the movement for educational equity and excellence.",
    annualBudget: "Over $5,000,000",
    contactName: "Sarah Mitchell",
    contactEmail: "sarah.mitchell@teachforamerica.org",
    contactPhone: "(212) 555-0147",
    contactTitle: "Director of Development",
    projectTitle: "Rural Teacher Pipeline Expansion",
    projectDescription: "Expanding corps member recruitment and placement in 10 underserved rural districts across the Southeast, providing two-year teaching commitments with ongoing professional development and community integration support.",
    amountRequested: "$500,000",
    projectTimeline: "24 months starting August 2027",
    targetPopulation: "K-12 students in underserved rural school districts",
    programAreas: "Education, Workforce Development, Rural Communities",
    referralSource: "Referral from another organization",
  },
];
